### ISSUE TITLE
Update DefaultRenderHook to use current ResponseWriter status, if any.

### ISSUE THREAD

**Issue by wI2L** [loopfz/gadgeto#54]
https://github.com/loopfz/gadgeto/blob/775b39d121995290dc1fd964f251db983d99003d/tonic/tonic.go#L101

The current `RenderHook` uses the default route status code that is declared when binding a handler with tonic. I would like to be able in my handler to override this default status code (say `200 OK` is default, but `204 No Content` is also possible).

Gin does provide access to the `gin.ResponseWriter` via the context, so we could check if the status has been overrided by the handler and use it instead of the default.

Implementation would look like:

```go
func DefaultRenderHook(c *gin.Context, statusCode int, payload interface{}) {
	status := c.Writer.Status()
	if status == 0 {
		code = statusCode // use default provided by Tonic
	}
	if payload != nil {
		if gin.IsDebugging() {
			c.IndentedJSON(status, payload)
		} else {
			c.JSON(status, payload)
		}
	} else {
		c.Status(status)
	}
}
```

Thoughts @rbeuque74 @loopfz ?

**Comment by wI2L** [comment]
@rbeuque74 @loopfz Up ! Thoughts ?

**Comment by loopfz** [comment]
lgtm, @rbeuque74 ?

**Comment by rbeuque74** [comment]
Go :) :+1:
