### ISSUE TITLE
How to add RegisterTagNameFunc using Tonic

### ISSUE THREAD

**Issue by hmajid2301** [loopfz/gadgeto#71]
Relevant issue I created on the wrong repo (for more context): https://github.com/wI2L/fizz/issues/46

What is the best way to match the functionality if I update the function `initValidator` from `handler.go`

```go
func initValidator() {
	validatorOnce.Do(func() {
		validatorObj = validator.New()
		validatorObj.SetTagName(ValidationTag)
		validatorObj.RegisterTagNameFunc(func(fld reflect.StructField) string {
			name := strings.SplitN(fld.Tag.Get("json"), ",", 2)[0]
			if name == "-" {
				return ""
			}
			return name
		})
	})
}
```

When I do `e.(tonic.BindError).ValidationErrors().Field()` I get the JSON struct tag name (i.e. `rules_url`) vs the struct field name (`RulesURL`).

What is the correct way to register a tag name function using tonic ? Thanks.

**Comment by jubrilee** [comment]
Running into this issue as well and would like to see this functionality supported
