### ISSUE TITLE
Upgrade validator dependency to v10

### ISSUE THREAD

**Issue by gablemire** [loopfz/gadgeto#73]
Gin has moved towards validator v10, but tonic has not. Because of this, it prevents `tonic.RegisterValidation` from working properly in Go 1.16, especially since validator v9 does not expose a `go.mod` file.

Upgrade should be straight forward.

**Comment by loopfz** [comment]
Thanks for the heads up, will tackle soon

**Comment by loopfz** [comment]
Fixed by #74, thanks
